commands: 
- "configure terminal"
- "interface {{ interface_olt }}"
- "no onu {{ onu_id }}"
- "exit"
- "interface {{ interface_olt }}"
- "onu {{ onu_id }} type ALL sn {{ sn }}"
- "exit"
- "interface {{ interface_onu }}"
- "name {{ customer.name }}"
- "description {{ customer.address }}"
- "sn-bind enable sn"
- "tcont 1 name PPPOE profile UP-100MB"
- "gemport 1 name CIGNAL tcont 1"
- "service-port 1 vport 1 user-vlan {{ vlan }} vlan {{ vlan }}"
- "gemport 1 traffic-limit downstream DOWN-100M"
- "exit"
- "pon-onu-mng {{ interface_onu }}"
- "service CIGNAL gemport 1 cos 0 vlan {{ vlan }}"
- "wan-ip 1 mode pppoe username {{ customer.pppoe_user }} password {{ customer.pppoe_pass }} vlan-profile vlan{{ vlan }} host 1"
- "wan-ip 1 ping-response enable traceroute-response enable"
- "security-mgmt 2 ingress-type wan mode forward state enable protocol web"
- "interface eth eth_0/1 state lock"
- "interface eth eth_0/2 state lock"
- "interface eth eth_0/3 state lock"
- "interface eth eth_0/4 state lock"
- "exit"
- "exit"
